### ISSUE TITLE
Refactor prompt commands to be plugin based

### ISSUE THREAD

**Issue by ixje** [CityOfZion/neo-python#623]
_Rationale:_ 
Currently [prompt.py](https://github.com/CityOfZion/neo-python/blob/master/neo/bin/prompt.py) over time evolved into a beast of `if/else` branches for command handling with several issues such as:

- Commands present but missing from the `help` output
- Commands present but not part of the auto completer
- Some commands have been extracted to live under `/neo/Prompt/Commands/` yet still are dependent on proper integration in `prompt.py`
- Most commands are suboptimally covered in automated testing and/or poorly testable
- Custom commands require patching after every update

_Goal:_
Turn console commands into a plugin based system that's easily testable without having to run the actual prompt. They can live under `/neo/Prompt/Commands/`. They should be reusable with another front-end (see the related issue [Create more interactive and clean CLI](https://github.com/CityOfZion/neo-python/issues/624))

**Command TODO list**
- [x] quit
- [x] help

- [x] show
   - [x] block
   - [x] header {index/hash}
   - [x] tx {hash}
   - [x] mem # returns memory in use and number of buffers
   - [x] nodes # returns connected peers
   - [x] state
   - [x] notifications {block_number or address}
   - [x] account {address} # returns account state
   - [x] asset
   - - [x] {assetId} # returns asset state
   - [x] contract 
   - - [x] {contract hash} # returns contract state

- [x] config 
   - [x] debug-notify {on/off}
   - [x] sc-events {on/off}
   - [x] maxpeers {num_peers}
   - [x] node-requests {reqsize} {queuesize}
   - [x] output
   - [x] vm_log
   - [x] compiler-nep8 {on/off}

- [x] wallet
   - [x] create
   - [x] open 
   - [x] close
   - [x] {verbose}
   - [x] claim (max_coins_to_claim)
   - [x] rebuild {start block}
   - [x] create_addr {number of addresses <= 3}
   - [x] delete_addr {addr}
   - [x] alias {addr} {title}
   - [x] token
   - - [x] delete {token_contract_hash}
   - - [x] send {token symbol} etc
   - - [x] send_from {token symbol} etc
   - - [x] approve {token symbol} etc
   - - [x] allowance {token symbol} etc
   - - [x] mint {token symbol} {mint_to_addr} etc
   - - [x] register {addr} etc
   - - [x] history {token symbol}
   - [x] unspent (neo/gas)
   - [x] split {addr} {asset} etc
   - [x] send {assetId or name} etc
   - [x] sendmany {number of outgoing tx} etc
   - [x] sign {transaction in JSON format}
   - [x] import
   - - [x] nep2
   - - [x] wif
   - - [x] multisig_addr
   - - [x] token
   - - [x] contract_addr
   - - [x] watch_addr
   - [x] export
   - - [x] wif
   - - [x] nep2

- [x] search
  - [x] asset {query}
  - [x] contract {query}

#need a good group command name for development related activities>
- [x] to be named group  
   - [x] build {path/to/file.py} etc
   - [x] load_run {path/to/file.avm} etc
   - [x] testinvoke {contract hash} etc
   - [x] debugstorage {on/off/reset}
   - [x] import contract {path/to/file.avm} etc

**TODO various**
- [ ] separate presentation from implementation (move `execute()` implementations to separate functions such that others can call them without having to go through `WalletCommand X`)
- [x] after the previous item, make sure console themes still work. This requires "Format Tokens" from the `prompt_toolkit` package, but it should only be applied when used in the CLI. Meaning; the business logic should not be coupled to a `PromptInterface()` instance because that's the one who creates the theme tokens. solution idea: supply print function as param.
- [x] Move wallet commands related to address in its own `address` group ( alias, create, delete, split)
- [x] `Wallet` is becoming huge. Split file into multiple (e.g. based on subgroup)
- [x] check all command help output and validate consistent use of `argument` vs `parameter`.
- [x] Update readthedocs documentation

**Comment by LysanderGG** [comment]
I'd like to try and do this issue.

I suggest the following:
- Open PR with the basic structure for `prompt.py` and one or two commands moved to `/neo/Prompt/Commands/`
- Review ^
- Move the other commands once the structure is ok.

What do you think?

**Comment by ixje** [comment]
@LysanderGG Sounds good! Looking forward to your PR.

To help you a bit with direction setting, here are a bit more formal requirements:

- As a developer, I want to extend neo-python with custom commands, so that I can tune it to my needs
- As a user, I want my custom commands to survive updates, so that I can continue working without further interruption or required actions
- As a user, I want to get an overview of all available commands, so that I know what I can and can't do
- As a user, I want to get usage instructions if a command is not self explanatory, so that I know how to correctly call the command and know what the expected result is
- As a user, I want commands to auto complete, so that I won't make typing mistakes and so that I can work faster
- As a developer, I want to be able to unittest my custom commands, so that I can verify correct behaviour inside neo-python
- As a maintainer, I want the implementation to be independent from the presentation, so that we can change CLI/GUI with minimal effort

Note that everything is up for discussion. I tried to keep it high level as I don't have a 100% view at this point either, we learn as we go. Feel free to comment/suggest stuff here or reach out to me on Discord (same name)

**Comment by ixje** [comment]
@LysanderGG just checking in to see if you are in need of some input/ideas. Or if you lost interest, please let us know so we don't duplicate work if somebody else shows interest. Thanks! 👍

**Comment by LysanderGG** [comment]
@ixje I started thinking about it and writing some code this week, I'll contact you on Discord for a few questions :)

**Comment by ixje** [comment]
I gave a moment of thought about how we could group commands.

```
quit
help

show
- block {index/hash} (tx)
- header {index/hash}
- tx {hash}
- mem # returns memory in use and number of buffers
- nodes # returns connected peers
- state
- notifications {block_number or address}
- account {address} # returns account state
- asset
-- {assetId} # returns asset state
-- search {query} <- not ideal. open for ideas how to structure otherwise.
- contract 
-- {contract hash} # returns contract state
-- search {query}


config 
- debug {on/off}
- sc-events {on/off}
- maxpeers {num_peers}
- node-requests {reqsize} {queuesize}
- node-requests {slow/normal/fast}
- compiler-nep8 {on/off}

wallet
- create
- open 
- close
- {verbose}
- claim (max_coins_to_claim)
- migrate
- rebuild {start block}
- create_addr {number of addresses <= 3}
- delete_addr {addr}
- delete_token {token_contract_hash}
- alias {addr} {title}
- tkn_send {token symbol} {address_from} {address to} {amount}
- tkn_send_from {token symbol} {address_from} {address to} {amount}
- tkn_approve {token symbol} {address_from} {address to} {amount}
- tkn_allowance {token symbol} {address_from} {address to}
- tkn_mint {token symbol} {mint_to_addr} (--attach-neo={amount}, --attach-gas={amount})
- tkn_register {addr} ({addr}...) (--from-addr={addr})
- tkn_history {token symbol}
- unspent (neo/gas)
- split {addr} {asset} {unspent index} {divide into number of vins}
- send {assetId or name} {address} {amount} (--from-addr={addr}) (--fee={priority_fee})
- sendmany {number of outgoing tx} (--change-addr={addr}) (--from-addr={addr}) (--fee={priority_fee})
- sign {transaction in JSON format}


# idea move the following also under the `wallet` group and rename them to `import_wif`, `import_nep2` etc?
import wif {wif}
import nep2 {nep2_encrypted_key}
import multisig_addr {pubkey in wallet} {minimum # of signatures required} {signing pubkey 1} {signing pubkey 2}...
import watch_addr {address}
import token {token_contract_hash}
import contract_addr {contract_hash} {pubkey}
export wif {address}
export nep2 {address}



#need a good group command name for development related activities>
build {path/to/file.py} (test {params} {returntype} {needs_storage} {needs_dynamic_invoke} {is_payable} [{test_params} or --i]) --no-parse-addr (parse address strings to script hash bytearray)
load_run {path/to/file.avm} (test {params} {returntype} {needs_storage} {needs_dynamic_invoke} {is_payable} [{test_params} or --i]) --no-parse-addr (parse address strings to script hash bytearray)
testinvoke {contract hash} [{params} or --i] (--attach-neo={amount}, --attach-gas={amount}) (--from-addr={addr}) --no-parse-addr (parse address strings to script hash bytearray)
debugstorage {on/off/reset}
import contract {path/to/file.avm} {params} {returntype} {needs_storage} {needs_dynamic_invoke} {is_payable}
```

It's a first idea. I'm open to input, changes. The above would give a base help output of
```
config
help
show
wallet
quit
// and one yet unnamed for development commands
```

**Comment by ixje** [comment]
@jseagrave21 I know you're eager looking for stuff to do. The plugin base is merged into the `refactor-prompt` branch, so we can start migrating commands to that branch according to the above structure. If you encounter a reason why the above structure doesn't work or does not make sense then let's discuss.

**Comment by LysanderGG** [comment]
@ixje @jseagrave21 
I'd suggest a markdown checklist that we could check when starting to work on a command so that we don't get to be two working on the same.

**Comment by ixje** [comment]
Good point. I created a todo list in the original issue. I don't think you guys can update it, but I can keep track of that. We'll have to post here in the comments to let each other know what command or command group we picked up to migrate to avoid conflicts/double work.

**Comment by jseagrave21** [comment]
1. Am I right in assuming from this https://github.com/CityOfZion/neo-python/blob/9b44392d370c3be9447786c06e53efd7d17be0bf/neo/Prompt/Commands/Wallet.py#L32-L35 
the corresponding commands are completed?

2. I would like to try to complete `send` and `sendmany`.

**Comment by jseagrave21** [comment]
@LysanderGG I like keeping them in the same folder. That is the example I have been following.

Also, @LysanderGG I can't get `wallet` to work it gives me this error:
```
neo> wallet
Could not execute command: list index out of range
  File "/usr/lib/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/c/users/jseag/neo/neo-python-refactor_prompt/venv/lib/python3.7/site-packages/twisted/_threads/_threadworker.py", line 46, in work
    task()
  File "/mnt/c/users/jseag/neo/neo-python-refactor_prompt/venv/lib/python3.7/site-packages/twisted/_threads/_team.py", line 190, in doWork
    task()
  File "/mnt/c/users/jseag/neo/neo-python-refactor_prompt/venv/lib/python3.7/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/mnt/c/users/jseag/neo/neo-python-refactor_prompt/venv/lib/python3.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/mnt/c/users/jseag/neo/neo-python-refactor_prompt/venv/lib/python3.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/mnt/c/users/jseag/neo/neo-python-refactor_prompt/venv/lib/python3.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/mnt/c/users/jseag/neo/neo-python-refactor_prompt/neo/bin/prompt.py", line 1063, in run
    traceback.print_stack()
Traceback (most recent call last):
  File "/mnt/c/users/jseag/neo/neo-python-refactor_prompt/neo/bin/prompt.py", line 989, in run
    if arguments[-1] == 'help':
IndexError: list index out of range
```

**Comment by LysanderGG** [comment]
@jseagrave21 
Same folder but different files?

`wallet` is the only command I didn't test, I'll fix later today. Thank you!
The code in `prompt.py` doesn't handle 1 word commands properly.

`wallet verbose` should work.

**Comment by jseagrave21** [comment]
> @jseagrave21
> Same folder but different files?
> 
> `wallet` is the only command I didn't test, I'll fix later today. Thank you!
> The code in `prompt.py` doesn't handle 1 word commands properly.
> 
> `wallet verbose` should work.

`wallet verbose` does work

**Comment by jseagrave21** [comment]
@ixje 
>```
> #need a good group command name for development related activities>
> build {path/to/file.py} (test {params} {returntype} {needs_storage} {needs_dynamic_invoke} {is_payable} [{test_params} or --i]) --no-parse-addr (parse address strings to script hash bytearray)
> load_run {path/to/file.avm} (test {params} {returntype} {needs_storage} {needs_dynamic_invoke} {is_payable} [{test_params} or --i]) --no-parse-addr (parse address strings to script hash bytearray)
> testinvoke {contract hash} [{params} or --i] (--attach-neo={amount}, --attach-gas={amount}) (--from-addr={addr}) --no-parse-addr (parse address strings to script hash bytearray)
> debugstorage {on/off/reset}
> import contract {path/to/file.avm} {params} {returntype} {needs_storage} {needs_dynamic_invoke} {is_payable}
> ```
How about "contract" for the new category.
Then the only change I would make would be from `import contract` to `contract import`..

**Comment by ixje** [comment]
I like the perspective of "contract" 👍 . The only small worry I have is with `contract` in the `show` group . How about calling it `sc` for `smart contract`? Then the description can be something like `smart contract development` and we can change `import contract` to just `import` such that you get `sc import {parameters}` (along with `sc build`, `sc testinvoke` etc, nice and short for already long commands)

**Comment by jseagrave21** [comment]
@ixje I actually thought that having `contract` in the show group validated that contract meant "smart contract". I thought about `sc` or `smart contract` as well but thought that `contract` was better because their is already presidence for its use.

**Comment by LysanderGG** [comment]
@jseagrave21 👍  Thank you!
I will keep on working on the wallet commands: finish the test PR and move other commands.

**Comment by jseagrave21** [comment]
> _Rationale:_
> Currently [prompt.py](https://github.com/CityOfZion/neo-python/blob/master/neo/bin/prompt.py) over time evolved into a beast of `if/else` branches for command handling with several issues such as:
> 
> * Commands present but missing from the `help` output
> * Commands present but not part of the auto completer
> * Some commands have been extracted to live under `/neo/Prompt/Commands/` yet still are dependent on proper integration in `prompt.py`
> * Most commands are suboptimally covered in automated testing and/or poorly testable
> * Custom commands require patching after every update
> 
> _Goal:_
> Turn console commands into a plugin based system that's easily testable without having to run the actual prompt. They can live under `/neo/Prompt/Commands/`. They should be reusable with another front-end (see the related issue [Create more interactive and clean CLI](https://github.com/CityOfZion/neo-python/issues/624))
> 
> **Command TODO list**
> 
> * [x]  quit
> * [x]  help
> * [ ]  show
>   
>   * [ ]  block
>   * [ ]  header {index/hash}
>   * [ ]  tx {hash}
>   * [ ]  mem # returns memory in use and number of buffers
>   * [ ]  nodes # returns connected peers
>   * [ ]  state
>   * [ ]  notifications {block_number or address}
>   * [ ]  account {address} # returns account state
>   * [ ]  asset
>   * * [ ]  {assetId} # returns asset state
>   * * [ ]  search {query} <- not ideal. open for ideas how to structure otherwise.

@ixje I think we should have `search` as a separate method group. I foresee us adding more search methods as NEO's complexity/accessibility increases. So, for now:

- [ ] search
  - [ ] asset {query}
  - [ ] contract {query}

Thoughts?

**Comment by ixje** [comment]
Guy's please keep the PR's small, about 3-4 commands max per PR. Judge for yourself how many lines of code+test need to be reviewed and adjust accordingly. If a group has a lot of commands, then stage the PR's in sequence or get the group base in and then PR the subcommands separately. 

Keep in mind that just because something was already tested in the old code base, doesn't mean they shouldn't have another critical look in their new environment. 

Thanks for understanding 🙏

**Comment by jseagrave21** [comment]
@ixje  Could you update the original issue to reflect

- [ ] search
  - [ ] asset {query}
  - [ ] contract {query}

?

**Comment by jseagrave21** [comment]
> I like the perspective of "contract"  . The only small worry I have is with `contract` in the `show` group . How about calling it `sc` for `smart contract`? Then the description can be something like `smart contract development` and we can change `import contract` to just `import` such that you get `sc import {parameters}` (along with `sc build`, `sc testinvoke` etc, nice and short for already long commands)

@ixje Have you decided on a label for the developer's group? I think I would like to tackle that next but I could also work on the config group first.

**Comment by jseagrave21** [comment]
@ixje @LysanderGG Based on a PM conversation with @ixje, the developer's group will be named the `sc` group. I am working on refactoring it now.

**Comment by jseagrave21** [comment]
@ixje @LysanderGG How do we want to implement commands which don't fall under any of the current groups? For example, I just found these two:
https://github.com/CityOfZion/neo-python/blob/e3780126f9cf8175f9f3c7ad27f36f2baae20508/neo/bin/prompt.py#L1018-L1021

**Comment by ixje** [comment]
Let's collect them for the time being and decide in the end

**Comment by jseagrave21** [comment]
@ixje @LysanderGG when attempting to refactor `build` and `load_and_run`, I run into issues with `ParameterDesc`. Within the former commands are required parameters for optional commands which is not currently supported (i.e. there is no logic to yield the current "help" line: `build {path/to/file.py} (test {params} {returntype} {needs_storage} {needs_dynamic_invoke} {is_payable} [{test_params} or --i]) --no-parse-addr (parse address strings to script hash bytearray)`).
Some examples of using this code are:
- `build path.py test 0710 05 True False False [input1, input2]`
- `build path.py test 0710 05 True False False --i` where `--i` directs prompted input entry
- `build path.py test 0710 05 True False False [input1, input2] --no-parse-addr` where `--no-parse-addr` directs to parse address strings to script hash bytearray

Similar issues arise when working with commands with deeper sub commands such as the `wallet token` group (which @ixje  is looking at now).

I have spent some time thinking about this and I think we need to decide as a team what the path forwards is because I think it will mean changing `ParameterDesc` and possibly other functions within `CommandBase.py`.

**Comment by jseagrave21** [comment]
While we are figuring this out, I think I might try to work on the `config` group since it should be pretty straightforward.

**Comment by ixje** [comment]
fyi; i'm looking into the `wallet Token` group.

**Comment by LysanderGG** [comment]
Referring to the list here (if nothing is missing) 
https://github.com/CityOfZion/neo-python/blob/development/neo/bin/prompt.py#L95

It seems that `build` and `load_run` are the only commands with this kind of behaviour.
`wallet token xxx` seems fine because it is possible to have multiple levels of subcommands.
So it would be 
```
CommandWallet
 |__ CommandWalletToken
       |___ CommandWalletTokenSend
       |___ CommandWalletTokenSendFrom
       |___ CommandWalletTokenApprove
...
```

I have 2 suggestions that would work with the current `CommandBase`:

1. Would it be possible to move the `test` before the argument? It would become 
`build path.py`
`build test path.py 0710 05 True False False [input1, input2]`

2. Do the same as `wallet tkn_send` , i.e. use one optional attribute that takes a list (like `--tx-attr=[{"usage": <value>,"data":"<remark>"}, ...])'`
it would give `build path.py --test=[0710 05 True False False [input1, input2]]` we could separate by space or comma.

**Comment by jseagrave21** [comment]
The problem I see is that `BuildAndRun` and `LoadAndRun` both feed into `DoRun`. Unless we want to revise their functionality, the previous options will not work.

**Comment by ixje** [comment]
I'd favour option 1 over option 2.

@jseagrave21 can you elaborate what problem you foresee with those commands both calling `DoRun`?

**Comment by jseagrave21** [comment]
It may be a simple issue (I haven't thought about it too much) but the inputs are read based on position currently. So, making `arg[1]` variable will introduce errors and the need for new logic.
https://github.com/CityOfZion/neo-python/blob/e3780126f9cf8175f9f3c7ad27f36f2baae20508/neo/Prompt/Commands/BuildNRun.py#L46-L77

**Comment by ixje** [comment]
I see your point now. I think we should adjust `DoRun` to work with our intentions instead of trying to work around it.

**Comment by jseagrave21** [comment]
Okay, so is option 1 the final verdict?

**Comment by jseagrave21** [comment]
I have made some significant progress on the `config` group. I will finish it before moving on (potentially back to the `sc` group).

**Comment by ixje** [comment]
picking up `wallet import`, specifically `nep2` + `wif`

**Comment by ixje** [comment]
picking up `wallet import watchaddr`

**Comment by ixje** [comment]
picking up `wallet import multisig_addr`

**Comment by ixje** [comment]
picked up `token approve` and will also take `token allowance`.

**Comment by ixje** [comment]
quickly doing `config nep8` to finish that group

**Comment by LysanderGG** [comment]
picking up `wallet import token` and `wallet import contract_addr`

**Comment by jseagrave21** [comment]
Hey guys I am moving across country this week and the next so I will try to help with reviews where I can and small stuff possibly but I don't think it would be fair for me to claim any additional commands right now.

**Comment by LysanderGG** [comment]
@jseagrave21 got it, thank you for the notice.
Thank you so much for all the help on this issue!

Have a good holiday! 🎅

**Comment by jseagrave21** [comment]
Thanks @LysanderGG! You too!

**Comment by ixje** [comment]
TODO: both `search contract` and `search asset` without arguments throw stack traces. Perhaps due to merging, but we need to fix it.
```
neo> search contract
Could not execute command: 'NoneType' object has no attribute 'casefold'
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/erik/Documents/code/neo-python/venv/lib/python3.6/site-packages/twisted/_threads/_threadworker.py", line 46, in work
    task()
  File "/Users/erik/Documents/code/neo-python/venv/lib/python3.6/site-packages/twisted/_threads/_team.py", line 190, in doWork
    task()
  File "/Users/erik/Documents/code/neo-python/venv/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/Users/erik/Documents/code/neo-python/venv/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/Users/erik/Documents/code/neo-python/venv/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/Users/erik/Documents/code/neo-python/venv/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "neo/bin/prompt.py", line 223, in run
    traceback.print_stack()
Traceback (most recent call last):
  File "neo/bin/prompt.py", line 209, in run
    cmd.execute(arguments)
  File "/Users/erik/Documents/code/neo-python/neo/Prompt/Commands/Search.py", line 30, in execute
    return self.execute_sub_command(item, arguments[1:])
  File "/Users/erik/Documents/code/neo-python/neo/Prompt/CommandBase.py", line 74, in execute_sub_command
    return self.__sub_commands[id].execute(arguments)
  File "/Users/erik/Documents/code/neo-python/neo/Prompt/Commands/Search.py", line 61, in execute
    contracts = Blockchain.Default().SearchContracts(query=item)
  File "/Users/erik/Documents/code/neo-python/neo/Implementations/Blockchains/LevelDB/LevelDBBlockchain.py", line 235, in SearchContracts
    query = query.casefold()
AttributeError: 'NoneType' object has no attribute 'casefold'
```

**Comment by jseagrave21** [comment]
> TODO:
> 
> * [ ]  both `search contract` and `search asset` without arguments throw stack traces. Perhaps due to merging, but we need to fix it.

I should be able to handle this @ixje @LysanderGG

**Comment by ixje** [comment]
I'll pickup `config debugstorage {on/off/reset}`

**Comment by ixje** [comment]
picking up the final command `testinvoke {contract hash} etc` 🎉

**Comment by ixje** [comment]
I'm going to update the documentation

**Comment by ixje** [comment]
I'll update #731 and then I think we can consider this issue done. We could arguably do more refactoring, but perhaps it's time to merge and get a new version out. This is already a major update and great improvement.

Thoughts? @jseagrave21 @LysanderGG

**Comment by jseagrave21** [comment]
What about the first ToDo? Is there a reason to merge before it is finished? We could split up the tasking for a quick push before the finish line?

**Comment by ixje** [comment]
I think the feedback will come once the community starts using it. I want to merge it into dev first, wait for a day of 4 so people can try/report stuff. Then merge to main.

**Comment by jseagrave21** [comment]
Sounds great!

**Comment by jseagrave21** [comment]
Minor comment:
In `wallet address create` the first param is "number of addresses", which doesn't really stick with the whole one-word rule.
I recommend converting to "integer" for
```
p1 = ParameterDesc('integer', 'the number of addresses to create')
```
